
export const BEGIN_AJAX_CALL= "BEGIN_AJAX_CALL";
export  const END_AJAX_CALL= "END_AJAX_CALL";
export const GET_ALL_JOBS="GET_ALL_JOBS"
export const ADD_ASSESTMENT='ADD_ASSESTMENT'
export const NEW_JOB='NEW_JOB'
export const NEW_EVENT='NEW_EVENT'
export const UPDATE_JOB ='UPDATE_JOB'
export const UPDATE_FIELD='UPDATE_FIELD'
export const EVENT_UPDATED='EVENT_UPDATED'
export const UPDATE_EVENT_FIELD='UPDATE_EVENT_FIELD'
export const ADD_PARTICIPANT='ADD_PARTICIPANT'